version: '3.5'

services:

  php-apache-simple-crud:
    container_name: php-apache-simple-crud
    image: webdevops/php-apache:7.4
    volumes:
      - .:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
    ports:
      - 80:80
